### PR TITLE
x86 only compiler and assemble with gas than link with gcc

### PR DESCRIPTION
**Pull request by tony0620emma**
I rewrite the x64 compiler to x86 only compiler
And make some instruction changes (AT&T syntax)
assemble with GAS and than link with GCC
It can be better , I will optimize them later

### CODE REVIEW

**Comment by jserv** [comment]
Great work! Can you rebase to [master](https://github.com/jserv/jit-construct) branch?

**Comment by tony0620emma** [comment]
I don't know how to rebase 
I type "git rebase master" but nothing happened....
What should I do?

**Comment by tony0620emma** [comment]
I need to declare my putchar because if I don't do it , the program will go down , and I guess it's because I need to specify the exact system call

**Comment by jserv** [comment]
@tony0620emma : No problem at all. Please check the great material about "git rebase": https://ihower.tw/blog/archives/6704

**Comment by jserv** [comment]
To be more consistent with the x86_64 version, I wish you can investigate the way to perform system calls inside JIT compiler.

**Comment by tony0620emma** [comment]
I think I need to rewrite them
Check the memory alignment and system call
Also fix the conflicts

**Pull request closed without merging**
